### ISSUE TITLE
Subscriber -> Add working but throwing an exception

### ISSUE THREAD

**Issue by dotstormz** [LukaszMordawski/CampaignMonitorBundle#1]
```
$arguments = new FactoryArguments; // by this object you can pass various parameters
        $arguments->endpoint = 'subscribers';

        $data = $this->get('campaign_monitor.invoker')
            ->invoke($arguments, 'add', array(array(
                "EmailAddress"  => "john@doe.com",
                "Name"          => "John Doe",
            )));
```

Subscription is successful, however because the return HTTP status code is 201 an exception is thrown.

A successful subscription throws a 201 code as per this link: https://www.campaignmonitor.com/api/subscribers/

Simple change needed to the invoke.php file. 

```
if ($data->http_status_code != 200) {
```

Needs to be changed to 

```
if ($data->http_status_code != 200 && $data->http_status_code != 201) {
```

**Comment by lukasz-mordawski-old-account** [comment]
Thanks, I will take care about this later. Or, if you already fixed it locally, maybe could you create a pull request?

**Comment by lukasz-mordawski-old-account** [comment]
I merged your PR. Issue is closed.
